#define TAM_ARCHIVO 100
#define TAM_PALABRA 50
#define TAM_MSG 1000
#define CONSOLA_RANK 0

#define TAG_ADD_START 1
#define TAG_ADD_RECEPTOR 2
#define TAG_ADD_WORD 3
#define TAG_LOAD 4
#define TAG_LOADED 5 
#define TAG_MEMBER 6
#define TAG_MAXIMUM_START 7
#define TAG_PALABRA 8
#define TAG_MAXIMUM_END 9
#define TAG_SKIP 10
#define TAG_QUIT 11