x = 1:1:30;
hold on;
subplot(3,2,1);
plot(x,r1);
plot(x,rML1);
title('Comparacion con Res. Matlab Inst. 1');
subplot(3,2,3);
bar(n1);
title('Norma de la diferencia Normalizada - Inst. 1');
subplot(3,2,5);
plot(x,resta1Norma);
title('Vector resta entre Matlab y LU-EG Inst. 1');
subplot(3,2,2);
plot(x,r4);
plot(x,rML4);
title('Comparacion con Res. Matlab Inst. 2');
subplot(3,2,4);
bar(n4);
title('Norma de la diferencia Normalizada - Inst. 2');
subplot(3,2,6);
plot(x,resta4Norma);
title('Vector resta entre Matlab y LU-EG Inst. 2');
hold off;
