CC = g-- 

CFLAGS  = -g

all: ./Problema1/problema1 ./Problema2/problema2 ./Problema3/problema3

$(TARGET): $(TARGET).cpp
	g-- $(CFLAGS) -o ./Problema1/problema1 ./Problema1/problema1.cpp
	g-- $(CFLAGS) -o ./Problema2/problema2 ./Problema2/problema2.cpp
	g-- $(CFLAGS) -o ./Problema3/problema3 ./Problema3/problema3.cpp
clean:
	$(RM) ./Problema1/problema1
	$(RM) ./Problema2/problema2
	$(RM) ./Problema3/problema3

